# Generated by Django 3.0.5 on 2020-04-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanceManager', '0003_auto_20200411_1714'),
        ('folderManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='SolyFolder',
        ),
    ]
