# Generated by Django 3.0.5 on 2020-04-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Nothing yet', max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(default='No named yet', max_length=50)),
                ('author', models.CharField(default='No author', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='suggested_files/')),
                ('link', models.CharField(default='No link', max_length=1000)),
                ('tags_json', models.CharField(default='[]', max_length=1000)),
                ('author_name', models.CharField(blank=True, default='', max_length=50)),
                ('author_email', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
