# Generated by Django 3.0.5 on 2020-04-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instanceManager', '0003_auto_20200411_1714'),
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='label',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='instance_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instanceManager.Instance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggesteddocument',
            name='document',
            field=models.FileField(blank=True, upload_to='suggested_files/'),
        ),
        migrations.AlterField(
            model_name='suggesteddocument',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
