# Generated by Django 3.0.5 on 2020-04-11 18:13

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0002_auto_20200411_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggesteddocument',
            old_name='document',
            new_name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
