# Generated by Django 3.0.5 on 2020-04-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instanceManager', '0003_auto_20200411_1714'),
        ('fileManager', '0003_auto_20200411_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolyFile',
            fields=[
                ('instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instanceManager.Instance')),
                ('url', models.CharField(max_length=200)),
            ],
            bases=('instanceManager.instance',),
        ),
        migrations.CreateModel(
            name='SuggestedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='suggested_files/')),
                ('description', models.CharField(default='[]', max_length=1000)),
                ('author_name', models.CharField(blank=True, default='', max_length=50)),
                ('author_email', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='instance_ptr',
        ),
        migrations.DeleteModel(
            name='SuggestedDocument',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
