# Generated by Django 3.0.5 on 2020-04-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instanceManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instanceManager.Instance'),
        ),
    ]
